### ISSUE TITLE
Designing API

### ISSUE THREAD

**Issue by jasokolowska** [jasokolowska/financial-app#2]
## Summary

Designing API in cooperation with Frontend Team.

## Implementation Details

- choosing a specific tool, ex. swagger
- setting up endpotints with specific body

**Comment by jasokolowska** [comment]
By cloning project locally and running doker-compose up you can access proposition of api on:
http://localhost:8080/swagger-ui/index.html

Please give me a feedback, what can I improve.

**Comment by jasokolowska** [comment]
![Image](https://github.com/jasokolowska/financial-app/assets/83209613/27d3ac4c-3995-4a7a-bb0f-4c5bd2800055)

**Comment by kamilsobik** [comment]
On this moment, for me this is perfect ❤
